development:
  cloud_name: dvofemxzc
  api_key: "622437619698923"
  api_secret: 9B_rmJ9eO0OYZAq2kMKYd-cDER4
  enhance_image_tag: true
  static_file_support: false

production:
  cloud_name: dvofemxzc
  api_key: "622437619698923"
  api_secret: 9B_rmJ9eO0OYZAq2kMKYd-cDER4
  enhance_image_tag: true
  static_file_support: false
