default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  username: dev
  password: alliswell
  database: ENV['DB_NAME']

test:
  <<: *default
  database: ENV['DB_NAME']
  username: ENV['DB_USER_NAME']
  password: ENV['DB_PASSWORD']

production:
  <<: *default
  database: ENV['DB_NAME']
  username: ENV['DB_USER_NAME']
  password: ENV['DB_PASSWORD']

  # database: twitter
  # username: postgres
  # password: postgres
  # host: database-1.clfzloadxh6b.ap-northeast-1.rds.amazonaws.com
  # port: 5432
