default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: ENV['DB_NAME']
#   username: ENV['DB_USER_NAME']
#   password: ENV['DB_PASSWORD']

test:
  <<: *default
  database: ENV['DB_NAME']
  username: ENV['DB_USER_NAME']
  password: ENV['DB_PASSWORD']

production:
  <<: *default
  database: ENV['DB_NAME']
  username: ENV['DB_USER_NAME']
  password: ENV['DB_PASSWORD']
